title: wenwen12345's Blog
baseURL: "https://blog.liaowen.us.kg/"
theme: PaperModX

enableRobotsTXT: true
enableEmoji: true

params:
  description: "一个博客"
  author: Reorx
  images:
    - cover.png
  favicon: favicon.ico
  #logo:
  #  icon: images/logo.svg
  DateFormat: "2006-01-02"
  useCustomAnalytics: true
  mainSections:
    - posts
    - notes

  # theme params
  DisableLanguageSwitch: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: false
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - twitter
    - telegram
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  homeInfoParams:
    Title: "PaperModX"
    Content: |
      Welcome to demo of hugo's theme PaperModX.

      - **PaperModX** is a simple but fast and responsive theme with useful feature-set that enhances UX.

      - PaperModX is based on theme [PaperMod](https://github.com/adityatelange/hugo-PaperMod).

      To get started, please head to the [Docs](docs).

      To see examples of different contents, head to [examples tag](tags/example).

  commentSystems:
  #  disqus:
  #    shortname: reorx
    remark42:
      url: https://remark42.liaowen.us.kg
      site: blog
  #  telegramWidget:
  #    channel: reorx_share
  #    accentColor: "9077e1"
  #    limit: 20
  defaultCommentSystems:
    remark42: true

permalinks:
  posts: "/:section/:year/:month/:slugorfilename/"
  notes: /:section/:year/:month/:slugorfilename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
  main:
    - name: 文章
      url: /posts/
      weight: 1
    - name: 搜索
      url: /search/
      weight: 2
    - name: 归档
      url: /archives/
      weight: 3
languages:
  en:
    languageName: "English"
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
